config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'

  resources :users, only: [:new, :create, :show] do
    resources :bookings, only: [:show, :index]
  end
  resources :bookings, only: [:destroy]
  resources :vehicles do
    resources :reviews, only: [:create, :new]
    resources :bookings, only: [:create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
  has_many :reviews
  validates :start_date, :end_date, presence: true
  def self.earliest_date
    start_at_values = Booking.pluck(:start_date)
    earliest_date = start_at_values.min
  end

  def self.sorted_bookings
    bookings = Booking.all
    sorted_objects = bookings.sort_by{|b| b.start_date}
  end

  def self.sort_bookings
    sorted_user_bookings = @user.bookings.sort_by{|b| b.start_date}
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :profile
  after_create :build_profileend
  end

   def build_profile
    Profile.create(user: self)

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :vehicle
    validates :rating, inclusion: 1..5
    validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile

  has_many :bookings
  has_many :vehicles
  has_many :vehicle_bookings, through: :vehicles, source: :bookings
  has_many :reviews, through: :bookings
  has_many :received_reviews, through: :vehicle_bookings, source: :review
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  validates :category, :model, :description, :price, :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos

 def self.pics
    ['https://images.unsplash.com/photo-1512203492609-972c16baa28b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80', 'https://images.unsplash.com/photo-1519119593016-06c9682c7f59?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80', 'https://images.unsplash.com/photo-1534787238916-9ba6764efd4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2978&q=80', 'https://i.pinimg.com/originals/71/38/75/713875ec85d0d7dd40e66a57d17c8558.jpg', 'https://i.pinimg.com/originals/53/7f/89/537f89e3619df2dd9615a5f35471fdb9.jpg', 'https://i.pinimg.com/originals/07/9d/83/079d8366a7a9662267c2096a53f3e09f.jpg', 'https://images.unsplash.com/photo-1528629297340-d1d466945dc5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1995&q=80', 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1908&q=80', 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80', 'https://images.unsplash.com/photo-1571188654248-7a89213915f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80', 'https://images.unsplash.com/photo-1545974452-caa213f76132?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80', 'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80', 'https://images.unsplash.com/photo-1549216963-72c1712c1196?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80', 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2703&q=80']
  end

  def average_rating
    if self.reviews.size > 0
        self.reviews.average(:rating)
    else
        nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @vehicle = Vehicle.new
    @review = Review.new
  end

  def new
    @booking = Booking.new
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking = Booking.new(booking_params)
    @booking.vehicle = @vehicle
    @booking.user = current_user
    if @booking.save
      redirect_to user_booking_path(current_user, @booking)
    else
      render 'vehicles/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:price, :start_date, :end_date, :confirmed, :vehicle)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @review = Review.new
    end

    def create
        @vehicle = Vehicle.find(params[:vehicle_id])
        @review = Review.new(review_params)
        @review.vehicle = @vehicle
        if @review.save
            redirect_to vehicle_path(@vehicle)
        else
            render 'vehicle/show'
        end
    end

    private

    def review_params
        params.require(:review).permit(:name, :content, :rating, :vehicle_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @bookings = Booking.all
    @vehicles = Vehicle.all
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
def index
    if params[:query].present?
      @vehicles = Vehicle.near(params[:query], 20)
      @markers = @vehicles.map do |vehicle|
        {
          lat: vehicle.latitude,
          lng: vehicle.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { vehicle: vehicle }),
          image_url: helpers.asset_url('bike.png')
        }
      end
    else
      @vehicles = Vehicle.all

      @vehicles = Vehicle.geocoded
      @markers = @vehicles.map do |vehicle|
        {
          lat: vehicle.latitude,
          lng: vehicle.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { vehicle: vehicle }),
          image_url: helpers.asset_url('bike.png')
        }
      end
    end
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    if @vehicle.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @booking = Booking.new
    @review = Review.new
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to user_path(current_user)
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:category, :model, :price, :description, :address, photos: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Your upcoming rides (<%= Booking.count %>)</h1>

<div class="container-2">
  <% @bookings.each do |booking| %>
  <div class="card-trip">
    <img src="https://upload.wikimedia.org/wikipedia/commons/4/41/Left_side_of_Flying_Pigeon.jpg" />
    <div class="card-trip-infos">
      <div>
        <h2>Booking #<%= link_to booking.id, user_booking_path(current_user, booking) %></h2>
        <p><%= booking.vehicle.category %> | <%= booking.vehicle.model %></p>
        <p><strong>FROM </strong><%= booking.start_date %> <strong>TO</strong> <%= booking.end_date %></p>
        <p><strong>Pick-up address:</strong> <%= booking.vehicle.address %></p>
      </div>
      <img src="https://organicthemes.com/demo/profile/files/2018/05/profile-pic.jpg" class="card-trip-user avatar-bordered" />
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Create a new Booking</h1>
<%= simple_form_for @booking do |f| %>
  <%= f.input :start_date %>
<% end %>

app/views/bookings/show.html.erb
<h1>Details about your booking #<%= @booking.id %></h1>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% if @vehicle.photos.attached?%>
      <div class="carousel-item active">
        <%= cl_image_tag @vehicle.photos.first.key, height: 500, width: 600, crop: :fill %>
      </div>
      <% @vehicle.photos.drop(1).each do |photo| %>
        <div class="carousel-item">
            <%= cl_image_tag photo.key, height: 500, width: 600, crop: :fill %>
        </div>
      <% end %>
    <% end %>

  </div>
<h4><%= @booking.vehicle.model %></h4>
  <div id="reviews">
    <% if @vehicle.reviews.blank? %>
      Be the first to leave a review for <%= @vehicle.model %>!
    <% else %>
      <% @vehicle.reviews.each do |review| %>
        <p><%= review.content %></p>
      <% end %>
    <% end %>
  </div>
  <div class="review-form">
    <h1 class="review-form__title">Review this vehicle</h1>
      <%= simple_form_for [@booking.vehicle, @review], :html=> { class: "review-form__form" } do |f| %>
          <%= f.input :name, :wrapper_html=> { class: "review-form__input-container" }, :input_html=> { class: "review-form__input" }, :label_html=> { class: "review-form__label"}%>
          <%= f.input :content, :wrapper_html=> { class: "review-form__input-container" }, :input_html=> { class: "review-form__input" }, :label_html=> { class: "review-form__label"}%>
          <%= f.input :rating, :wrapper_html=> { class: "review-form__input-container" }, :input_html=> { class: "review-form__input" }, :label_html=> { class: "review-form__label"}%>
          <%= f.button :submit, class: "review-form__button vehicle-form__button--submit" %>
      <% end %>
    </div>
  <div class="dashboard">
    <%= link_to "Dashboard", user_path(current_user), class: "review-form__button" %>
  </div>

<%= link_to "Back to all bookings", user_bookings_path(current_user), class: "btn btn-primary" %>

<%= link_to "Delete booking",
            booking_path(@booking),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentMyBike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_banner.html.erb
<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1542245796-946699811998?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Find your dream ride wherever you are.</h2>
          <p class="lead">Let us help you find the best vehicle.</p>
          <%= link_to 'Find a vehicle', 'vehicles', class: "btn btn-outline-light" %>
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1583409461426-20d5d4f7a66e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Join a community of like-minded individuals.</h2>
          <p class="lead">Want to make some money from your vehicle?. We got you.</p>
          <%= link_to 'List a vehicle', new_vehicle_path, class: "btn btn-outline-light" %>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>

app/views/pages/_searchform.html.erb
<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
     <div class="dropdown">
      <button onclick="myFunction()" class="dropbtn">Dropdown</button>
      <div id="myDropdown" class="dropdown-content">
       <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
          <a href="#location">Location</a>
          <a href="#start_date">Start date</a>
          <a href="#end_date">End Date</a>
          <a href="#type_of_vehicle">Type of Vehicle</a>
        </div>
      </div>
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<%= render 'banner' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Designed by the boys at InkFinder
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-bike">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://i.ibb.co/2sxTtnn/Copy-of-Contemporary-Simple-Black-House-Logo-2.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <div class="flexbox">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Dashboard", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">

        </li>
      </div>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ilbiscione", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.date_select :birthday %>
  <%= f.text_field :summary %>
  <%= f.button :submit, 'Save', class: 'submit' %>
 <% end %>

app/views/users/show.html.erb
<div class="user-container">
    <div class="user-tab">
        <button class="user-tab__links" data-tablinks="my-vehicles" id="defaultOpen">My Vehicles</button>
        <button class="user-tab__links" data-tablinks="my-bookings" >My Bookings</button>
    </div>
    <div class="vehicle-container tabcontent" id="my-vehicles">
        <div class="vehicle-card__header">
            <h2 class="">My vehicles</h2>
            <%= link_to "Create a new vehicle",  new_vehicle_path, class: "vehicle-card__button"%>
        </div>
        <% @user.vehicles.each do |vehicle| %>
            <% if vehicle.id === vehicle.bookings.pluck(:vehicle_id).first.to_i %>
                <div class="vehicle-card vehicle-card--promo">
            <% else %>
                <div class="vehicle-card">
            <% end %>
                <div class="vehicle-card__info-container">
                    <div class="vehicle-card__image-container">
                        <%= link_to vehicle_path(vehicle) do %>
                            <% if vehicle.photos.attached? %>
                                <%= cl_image_tag vehicle.photos.first.key, class: "vehicle-card__image" %>
                            <% end %>
                        <% end %>      
                    </div>
                    <div class="vehicle-card__info">
                        <h3 class="vehicle-card__title"><%= vehicle.category %></h3>
                        <span class="vehicle-card__price">£<%= vehicle.price %></span>
                        <span class="vehicle-card__model"><%= vehicle.model %></span>
                        <span class="vehicle-card__description"><%= vehicle.description %></span>
                    </div>
                    <div class="vehicle-card__review">
                        <% if vehicle.average_rating == nil %>
                            <p>No reviews</p>
                        <% else %>
                            <% for i in 1..5 do %>
                                <% if i <= vehicle.average_rating  %>
                                    <span class="fa fa-star checked"></span>
                                <% else %>
                                    <span class="fa fa-star"></span>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>

                    <div class="vehicle-card__destroy">
                        <%= link_to vehicle_path(vehicle), method: :delete, data: { confirm: "Are you sure?" }  do %>
                            <i class="far fa-trash-alt"></i>
                        <% end %>
                    </div>
                </div>
                <span class="vehicle-card__ribbon">
					<span class="vehicle-card__ribbon-text">Rented out</span>
				</span>
            </div>
        <% end %>
    </div>
    <div class="booking-container tabcontent" id="my-bookings">
        <div class="booking-card__header">
            <h2>Manage my bookings</h2>
        </div>
        <% @user.bookings.sorted_bookings.each do |b| %>
            <% if b.start_date == Booking.earliest_date  %>
                <div class="booking-card booking-card--promo">
            <% else %>
                <div class="booking-card">
            <% end %>
                <div class="booking-card__vehicle-container">
                    <div class="vehicle-card vehicle-card--booking">
                        <div class="vehicle-card__info-container">
                            <div class="vehicle-card__image-container">
                                <% if b.vehicle.photos.attached? %>
                                    <%= cl_image_tag b.vehicle.photos.first.key, class: "vehicle-card__image" %>
                                 <% end %>
                            </div>
                            <div class="vehicle-card__info">
                                <h3 class="vehicle-card__title"><%= b.vehicle.category %></h3>
                                <span class="vehicle-card__price">£<%= b.vehicle.price %></span>
                                <span class="vehicle-card__model"><%= b.vehicle.model %></span>
                                <span class="vehicle-card__description"><%= b.vehicle.description %></span>
                            </div>
                            <div class="vehicle-card__review">
                                <% if b.vehicle.average_rating == nil %>
                                    <p>No Reviews</p>
                                <% else %>
                                    <% for i in 1..5 do %>
                                        <% if i <= b.vehicle.average_rating  %>
                                            <span class="fa fa-star checked"></span>
                                        <% else %>
                                            <span class="fa fa-star"></span>
                                        <% end %>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="booking-card__container">
                    <div class="booking-card__info-container">
                        <div class="booking-card__info">
                            <h2 class="booking-card__id-title">Booking #<%= link_to b.id, user_booking_path(current_user, b) %></h2>
                            <p>Start date: <%= b.start_date.strftime("%I:%M%p, %d/%m/%y") %></p>
                            <p>End date: <%= b.end_date.strftime("%I:%M%p, %d/%m/%y") %></p>
                            <% if b.price == nil %>
                                <p>£<%= b.vehicle.price %></p>
                            <% else %>
                                <p>£<%= b.price %></p>
                            <% end%>
                        </div>
                    </div>
                    <div class="booking-card__destroy">
                        <%= link_to booking_path(b), method: :delete, data: { confirm: "Are you sure?" }  do %>
                            <i class="far fa-trash-alt"></i>
                        <% end %>
                    </div>
                    <div class="booking-card__review-card">
                        <%= link_to vehicle_path(b.vehicle_id) do %>
                            <i class="fas fa-comments"></i>
                            <span class="booking-card__review-comment">Review</span>
                        <% end %>
                    </div>
                </div>
                <span class="booking-card__ribbon">
					<span class="booking-card__ribbon-text">Coming up next</span>
				</span>
            </div>
        <% end %>
    </div>
</div>

app/views/vehicles/_bookingform.html.erb
<div class="booking form">
  <%= simple_form_for [booking, vehicle], path: vehicle_bookings_path do |f| %>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/vehicles/_info_window.html.erb
<h2><%= vehicle.model %></h2>
<h6>£<%= vehicle.price %>/day</h6>
<h6><%= vehicle.address %></h6>

<%= link_to"Book now", vehicle_path(vehicle), class: "btn btn-warning" %>

app/views/vehicles/index.html.erb
<div class="search-fo form-inline m-2">
  <%= form_tag vehicles_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Enter your city" %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

<% if params[:query].present? %>
  <div class="container container-2">
   <% @vehicles.each do |vehicle| %>
     <div class="card-trip">
      <% if vehicle.photos.attached? %>
        <%= cl_image_tag vehicle.photos.first.key%>
      <% end %>
     <div class="card-trip-infos">
        <div>
          <h2><%= vehicle.category %> | <%= vehicle.model %></h2>
          <p><%= link_to 'See more', vehicle_path(vehicle) %></p>
        </div>
        <h2 class="card-trip-pricing">£<%= vehicle.price %>/day</h2>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      </div>
    </div>
  <% end %>
  </div>
  <% end %>

<div class="map-con">
  <div id="map"
     style="width: 80%; height: 400px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class='homebtn'>
  <%= link_to"Back to home page", root_path, class: "btn btn-primary center my-3" %>
</div>